name: Daily Trending To TG

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    name: Build Go project
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.22.2
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: go build -v -o trending2tg main.go

    - name: Run
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        TRANSLATE_URL: ${{ secrets.TRANSLATE_URL }}
        LANGUAGES: ${{ secrets.LANGUAGES }}
      run: ./trending2tg

    - name: Add trends.db to tracking
      run: |
        if [ -f trends.db ]; then
          git add trends.db
        else
          echo "No trends.db file to add"
        fi

    - name: Check for changes
      id: git-status
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
      continue-on-error: true

    - name: Push to origin master
      if: steps.git-status.outputs.changed == 'true'
      run: |
        echo start push
        git config --global user.name "s1xu"
        git config --global user.email "s1xu@foxmail.com"
        git add -A
        git commit -m "$(date '+%Y-%m-%d')"
        git push