name: Daily Trending To TG

on: 
    workflow_dispatch:
    schedule:
        - cron: '0 12 * * *'

jobs:
    build:
        name: Build Go project
        runs-on: ubuntu-latest
        steps:
        - name: Set up Go 1.22.2
          uses: actions/setup-go@v5
          with:
            go-version: '1.22.2'

        - name: Check out code
          uses: actions/checkout@v3
    
        - name: Build
          run: go build -v -o trending2tg ./...
    
        - name: Run
          env:
            BotToken: ${{ secrets.BOT_TOKEN }}
            ChatID: ${{ secrets.CHAT_ID }}
            TranslateURL: ${{ secrets.TRANSLATE_URL }}
            Languages: ${{ secrets.LANGUAGES }}
          run: ./trending2tg
